name: Lint & Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform-lint:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform -chdir=terraform fmt -check

      - name: Terraform Validate
        run: |
          terraform -chdir=terraform init -backend=false
          terraform -chdir=terraform validate
